changing from ftp to https for downloading ncbi assembly summary tables, as the ftp way seems to be giving some trouble lately

diff --git a/bit-dl-ncbi-assemblies b/bit-dl-ncbi-assemblies
--- a/bit-dl-ncbi-assemblies
+++ b/bit-dl-ncbi-assemblies
@@ -102,23 +102,23 @@ rm -rf NCBI-accessions-not-downloaded.txt
 if [ ! -s ncbi_assembly_info.tsv ]; then
 
     printf "    ${GREEN}Downloading ncbi assembly summaries to be able to construct ftp links...${NC}\n\n"
-    curl --connect-timeout 30 --retry 10 ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt -o ncbi_assembly_info.tsv || echo "failed" > capture_any_dl_errors.tmp
+    curl --connect-timeout 30 --retry 10 https://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt -o ncbi_assembly_info.tsv || echo "failed" > capture_any_dl_errors.tmp
 
     # making sure file downloaded with no errors
     if [ -s capture_any_dl_errors.tmp ]; then
-        printf "\n\n  ${RED}Download of NCBI assembly summaries failed :(${NC}\n  Is your internet connection weak?\n\nExiting for now.\n\n"
+        printf "\n\n  ${RED}Download of NCBI assembly summaries failed :(${NC}\n  Is the internet connection weak?\n\nExiting for now.\n\n"
         rm -rf capture_any_dl_errors.tmp ncbi_assembly_info.tsv
         exit
     else
         rm -rf capture_any_dl_errors.tmp
     fi
 
-    curl --connect-timeout 30 --retry 10 ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt -o ncbi_RS_assembly_info.tmp || echo "failed" > capture_any_dl_errors.tmp
+    curl --connect-timeout 30 --retry 10 https://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt -o ncbi_RS_assembly_info.tmp || echo "failed" > capture_any_dl_errors.tmp
 
     # making sure file downloaded with no errors
     if [ -s capture_any_dl_errors.tmp ]; then
-        printf "\n\n  ${RED}Download of NCBI assembly summaries failed :(${NC}\n  Is your internet connection weak?\n\nExiting for now.\n\n"
-        rm -rf capture_any_dl_errors.tmp ncbi_assembly_info
+        printf "\n\n  ${RED}Download of NCBI assembly summaries failed :(${NC}\n  Is the internet connection weak?\n\nExiting for now.\n\n"
+        rm -rf capture_any_dl_errors.tmp ncbi_assembly_info.tsv
         exit
     else
         rm -rf capture_any_dl_errors.tmp
