adding bit-figshare-upload; fixing spacing issues from early scripts

diff --git a/bit-colnames b/bit-colnames
--- a/bit-colnames
+++ b/bit-colnames
@@ -5,16 +5,17 @@ RED='\033[0;31m'
 NC='\033[0m'
 
 if [ "$#" == 0 ] || [ $1 == "-h" ]; then
-  printf "\n  This script returns the column names (with number) from a tab-separated file.\n"
-  printf "  For version info, run \`bit-version\`.\n\n"
-  printf "    Usage:\n\t bit-colnames input.tsv\n\n"
-  exit
+    printf "\n  This script returns the column names (with number) from a tab-separated file.\n"
+    printf "  For version info, run \`bit-version\`.\n\n"
+    printf "    Usage:\n\t bit-colnames input.tsv\n\n"
+    exit
 fi
 
 if [ -f $1 ]; then
-  head -n1 $1 | tr "\t" "\n" | cat -n
+    
+    head -n1 $1 | tr "\t" "\n" | cat -n
 
 else
-  echo -e "     ${RED}Input file not found :/${NC}" >&2
-  exit 1
+    echo -e "     ${RED}Input file not found :/${NC}" >&2
+    exit 1
 fi
diff --git a/bit-remove-wraps b/bit-remove-wraps
--- a/bit-remove-wraps
+++ b/bit-remove-wraps
@@ -5,17 +5,17 @@ GREEN='\033[0;32m'
 NC='\033[0m'
 
 if [ "$#" == 0 ] || [ $1 == "-h" ]; then
-  printf "\n  This script removes line wraps from a fasta file. For version\n"
-  printf "  info, run \`bit-version\`.\n\n"
-  printf "    Usage:\n\t bit-remove-wraps input.fasta > new.fasta\n\n"
-  exit
+    printf "\n  This script removes line wraps from a fasta file. For version\n"
+    printf "  info, run \`bit-version\`.\n\n"
+    printf "    Usage:\n\t bit-remove-wraps input.fasta > new.fasta\n\n"
+    exit
 fi
 
 if [ -f $1 ]; then
-  awk '!/^>/ { printf "%s", $0; n="\n" } /^>/ { print n $0; n = "" } END { printf "%s", n }' "$1"
-  echo -e "     ${GREEN}Annoying line wraps removed! Cheers!${NC}" 1>&2
+    awk '!/^>/ { printf "%s", $0; n="\n" } /^>/ { print n $0; n = "" } END { printf "%s", n }' "$1"
+    echo -e "     ${GREEN}Annoying line wraps removed! Cheers!${NC}" 1>&2
 
 else
-  echo -e "     ${RED}Input file not found :/${NC}" 1>&2
-  exit 1
+    echo -e "     ${RED}Input file not found :/${NC}" 1>&2
+    exit 1
 fi
