changing ftp to https in bit-dl-ncbi-assemblies as something is up with the ftp way currently

diff --git a/bit-dl-ncbi-assemblies b/bit-dl-ncbi-assemblies
--- a/bit-dl-ncbi-assemblies
+++ b/bit-dl-ncbi-assemblies
@@ -101,7 +101,7 @@ fi
 if [ ! -s ncbi_assembly_info.tsv ]; then
 
     printf "    ${GREEN}Downloading ncbi assembly summaries to be able to construct ftp links...${NC}\n\n"
-    curl --connect-timeout 30 --retry 10 ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt -o ncbi_assembly_info.tsv || echo "failed" > capture_any_dl_errors.tmp
+    curl --connect-timeout 30 --retry 10 https://ftp.ncbi.nlm.nih.gov/genomes/genbank/assembly_summary_genbank.txt -o ncbi_assembly_info.tsv || echo "failed" > capture_any_dl_errors.tmp
 
     # making sure file downloaded with no errors
     if [ -s capture_any_dl_errors.tmp ]; then
@@ -112,7 +112,7 @@ if [ ! -s ncbi_assembly_info.tsv ]; then
         rm -rf capture_any_dl_errors.tmp
     fi
 
-    curl --connect-timeout 30 --retry 10 ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt -o ncbi_RS_assembly_info.tmp || echo "failed" > capture_any_dl_errors.tmp
+    curl --connect-timeout 30 --retry 10 https://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt -o ncbi_RS_assembly_info.tmp || echo "failed" > capture_any_dl_errors.tmp
 
     # making sure file downloaded with no errors
     if [ -s capture_any_dl_errors.tmp ]; then
